from _typeshed import Incomplete
from py4j.java_gateway import JavaObject
from pyspark.sql._typing import DateTimeLiteral, DecimalLiteral, LiteralType
from pyspark.sql.types import DataType
from pyspark.sql.window import WindowSpec
from typing import Any, TypeAlias, overload
from typing import (
    Literal,
    cast,
    overload,
    Any,
    Callable,
    Iterable,
    List,
    Optional,
    Tuple,
    TYPE_CHECKING,
    Union,
)
from typing import Any, Callable, overload, Generic, TypeVar, Union
from typing_extensions import LiteralString
from decimal import Decimal
import datetime


T = TypeVar("T", bound=LiteralString, contravariant=True)
TAlias = TypeVar("TAlias", bound=LiteralString, covariant=True)
T2 = TypeVar("T2", bound=LiteralString, covariant=True)
In = TypeVar("In", bound=LiteralString, covariant=True)
Out = TypeVar("Out", bound=LiteralString, covariant=True)
InOther = TypeVar("InOther", bound=LiteralString)
OutOther = TypeVar("OutOther", bound=LiteralString)
OutLit = TypeVar("OutLit", bound=LiteralString)
TSource = TypeVar("TSource", bound=LiteralString)
TResult = TypeVar("TResult", bound=LiteralString)
PrimitiveType = Union[bool, float, int, str]


__all__ = ['Column']
BinOp :TypeAlias= Callable[
    ["Column", Union["Column", "LiteralType", "DecimalLiteral", "DateTimeLiteral"]], "Column"
]

class Column(Generic[In, Out]):
    def __init__(self, jc: JavaObject) -> None: ...

    def __binary__op(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __neg__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __add__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __sub__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __mul__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __div__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __truediv__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __mod__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __radd__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rsub__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rmul__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rdiv__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rtruediv__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rmod__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __pow__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rpow__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __eq__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __ne__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __lt__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __le__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __ge__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __gt__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    eqNullSafe: Incomplete
    def __and__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __or__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __invert__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __rand__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __ror__(self, other: Column[InOther, OutOther] | LiteralType | DecimalLiteral | DateTimeLiteral) -> Column[Union[In, InOther], Union[Out, OutOther]]: ...
    def __contains__(self, item: Any) -> None: ...
    bitwiseOR: Incomplete
    bitwiseAND: Incomplete
    bitwiseXOR: Incomplete
    def getItem(self, key: Any) -> Column: ...
    def getField(self, name: Any) -> Column: ...
    def withField(self, fieldName: str, col: Column) -> Column: ...
    def dropFields(self, *fieldNames: str) -> Column: ...
    def __getattr__(self, item: Any) -> Column: ...
    def __getitem__(self, k: Any) -> Column: ...
    def __iter__(self) -> None: ...
    contains: Incomplete
    startswith: Incomplete
    endswith: Incomplete
    def like(self, other: str) -> Column: ...
    def rlike(self, other: str) -> Column: ...
    def ilike(self, other: str) -> Column: ...
    @overload
    def substr(self, startPos: int, length: int) -> Column: ...
    @overload
    def substr(self, startPos: Column, length: Column) -> Column: ...
    def isin(self, *cols: Any) -> Column: ...
    asc: Incomplete
    asc_nulls_first: Incomplete
    asc_nulls_last: Incomplete
    desc: Incomplete
    desc_nulls_first: Incomplete
    desc_nulls_last: Incomplete
    isNull: Incomplete
    isNotNull: Incomplete
    def alias(self, *alias: OutOther, **kwargs: Any) -> Column[In, OutOther]: ...
    name: Incomplete
    def cast(self, dataType: DataType | str) -> Column: ...
    astype: Incomplete
    def between(self, lowerBound: Column | LiteralType | DateTimeLiteral | DecimalLiteral, upperBound: Column | LiteralType | DateTimeLiteral | DecimalLiteral) -> Column: ...
    def when(self, condition: Column, value: Any) -> Column: ...
    def otherwise(self, value: Any) -> Column: ...
    def over(self, window: WindowSpec) -> Column: ...
    def __nonzero__(self) -> None: ...
    __bool__ = __nonzero__
