from _typeshed import Incomplete
from pyspark import SparkContext as SparkContext
from pyspark.errors import PySparkTypeError as PySparkTypeError, PySparkValueError as PySparkValueError
from pyspark.sql._typing import ColumnOrName[In, Out] as ColumnOrName[In, Out], ColumnOrName[In, Out]_ as ColumnOrName[In, Out]_, DataTypeOrString as DataTypeOrString, UserDefinedFunctionLike as UserDefinedFunctionLike
from pyspark.sql.column import Column as Column
from pyspark.sql.dataframe import DataFrame as DataFrame
from pyspark.sql.pandas.functions import PandasUDFType as PandasUDFType, pandas_udf as pandas_udf
from pyspark.sql.types import ArrayType as ArrayType, DataType as DataType, StringType as StringType, StructType as StructType
from pyspark.sql.udf import UserDefinedFunction as UserDefinedFunction
from pyspark.sql.udtf import UserDefinedTableFunction as UserDefinedTableFunction
from pyspark.sql.utils import get_active_spark_context as get_active_spark_context, has_numpy as has_numpy, to_str as to_str, try_remote_functions as try_remote_functions
from typing import Any, Callable, Literal, TypeVar, overload
from typing_extensions import LiteralString
T = TypeVar("T", bound=LiteralString, covariant=True)
In = TypeVar("In", bound=LiteralString, covariant=True)
Out = TypeVar("Out", bound=LiteralString, covariant=True)

def lit(col: Any) -> Column[Literal['lit'], Literal['expr'] ]: ...
def col(col: T) -> Column[T, T]: ...
column = col

def asc(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def desc(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sqrt(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_add(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_avg(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_divide(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_multiply(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_subtract(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_sum(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def abs(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def mode(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def max(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def min(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def max_by(col: ColumnOrName[In, Out], ord: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def min_by(col: ColumnOrName[In, Out], ord: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def count(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sum(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def avg(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def mean(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def median(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sumDistinct(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sum_distinct(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def product(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def acos(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def acosh(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def asin(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def asinh(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def atan(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def atanh(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def cbrt(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ceil(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ceiling(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def cos(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def cosh(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def cot(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def csc(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def e() -> Column[In, Literal['expr']]: ...
def exp(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def expm1(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def floor(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def log(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def log10(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def log1p(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def negative(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
negate = negative

def pi() -> Column[In, Literal['expr']]: ...
def positive(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def rint(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sec(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def signum(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sign(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sin(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sinh(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def tan(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def tanh(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def toDegrees(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def toRadians(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitwiseNOT(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitwise_not(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bit_count(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bit_get(col: ColumnOrName[In, Out], pos: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def getbit(col: ColumnOrName[In, Out], pos: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def asc_nulls_first(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def asc_nulls_last(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def desc_nulls_first(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def desc_nulls_last(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def stddev(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def std(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def stddev_samp(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def stddev_pop(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def variance(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def var_samp(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def var_pop(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_avgx(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_avgy(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_count(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_intercept(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_r2(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_slope(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_sxx(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_sxy(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regr_syy(y: ColumnOrName[In, Out], x: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def every(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bool_and(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def some(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bool_or(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bit_and(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bit_or(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bit_xor(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def skewness(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def kurtosis(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def collect_list(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_agg(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def collect_set(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def degrees(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def radians(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def atan2(col1: ColumnOrName[In, Out] | float, col2: ColumnOrName[In, Out] | float) -> Column[In, Literal['expr']]: ...
def hypot(col1: ColumnOrName[In, Out] | float, col2: ColumnOrName[In, Out] | float) -> Column[In, Literal['expr']]: ...
def pow(col1: ColumnOrName[In, Out] | float, col2: ColumnOrName[In, Out] | float) -> Column[In, Literal['expr']]: ...
power = pow

def pmod(dividend: ColumnOrName[In, Out] | float, divisor: ColumnOrName[In, Out] | float) -> Column[In, Literal['expr']]: ...
def width_bucket(v: ColumnOrName[In, Out], min: ColumnOrName[In, Out], max: ColumnOrName[In, Out], numBucket: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def row_number() -> Column[In, Literal['expr']]: ...
def dense_rank() -> Column[In, Literal['expr']]: ...
def rank() -> Column[In, Literal['expr']]: ...
def cume_dist() -> Column[In, Literal['expr']]: ...
def percent_rank() -> Column[In, Literal['expr']]: ...
def approxCountDistinct(col: ColumnOrName[In, Out], rsd: float | None = None) -> Column[In, Literal['expr']]: ...
def approx_count_distinct(col: ColumnOrName[In, Out], rsd: float | None = None) -> Column[In, Literal['expr']]: ...
def broadcast(df: DataFrame) -> DataFrame: ...
def coalesce(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def corr(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def covar_pop(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def covar_samp(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def countDistinct(col: ColumnOrName[In, Out], *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def count_distinct(col: ColumnOrName[In, Out], *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def first(col: ColumnOrName[In, Out], ignorenulls: bool = False) -> Column[In, Literal['expr']]: ...
def grouping(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def grouping_id(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def count_min_sketch(col: ColumnOrName[In, Out], eps: ColumnOrName[In, Out], confidence: ColumnOrName[In, Out], seed: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def input_file_name() -> Column[In, Literal['expr']]: ...
def isnan(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def isnull(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def last(col: ColumnOrName[In, Out], ignorenulls: bool = False) -> Column[In, Literal['expr']]: ...
def monotonically_increasing_id() -> Column[In, Literal['expr']]: ...
def nanvl(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def percentile(col: ColumnOrName[In, Out], percentage: Column | float | list[float] | tuple[float], frequency: Column | int = 1) -> Column[In, Literal['expr']]: ...
def percentile_approx(col: ColumnOrName[In, Out], percentage: Column | float | list[float] | tuple[float], accuracy: Column | float = 10000) -> Column[In, Literal['expr']]: ...
def approx_percentile(col: ColumnOrName[In, Out], percentage: Column | float | list[float] | tuple[float], accuracy: Column | float = 10000) -> Column[In, Literal['expr']]: ...
def rand(seed: int | None = None) -> Column[In, Literal['expr']]: ...
def randn(seed: int | None = None) -> Column[In, Literal['expr']]: ...
def round(col: ColumnOrName[In, Out], scale: int = 0) -> Column[In, Literal['expr']]: ...
def bround(col: ColumnOrName[In, Out], scale: int = 0) -> Column[In, Literal['expr']]: ...
def shiftLeft(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def shiftleft(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def shiftRight(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def shiftright(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def shiftRightUnsigned(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def shiftrightunsigned(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def spark_partition_id() -> Column[In, Literal['expr']]: ...
def expr(str: str) -> Column[In, Literal['expr']]: ...
@overload
def struct(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def struct(__cols: list['ColumnOrName[In, Out]_'] | tuple['ColumnOrName[In, Out]_', ...], /) -> Column[In, Literal['expr']]: ...
def named_struct(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def greatest(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def least(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def when(condition: Column, value: Any) -> Column[In, Literal['expr']]: ...
@overload
def log(arg1: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def log(arg1: float, arg2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ln(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def log2(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def conv(col: ColumnOrName[In, Out], fromBase: int, toBase: int) -> Column[In, Literal['expr']]: ...
def factorial(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def lag(col: ColumnOrName[In, Out], offset: int = 1, default: Any | None = None) -> Column[In, Literal['expr']]: ...
def lead(col: ColumnOrName[In, Out], offset: int = 1, default: Any | None = None) -> Column[In, Literal['expr']]: ...
def nth_value(col: ColumnOrName[In, Out], offset: int, ignoreNulls: bool | None = False) -> Column[In, Literal['expr']]: ...
def any_value(col: ColumnOrName[In, Out], ignoreNulls: bool | Column | None = None) -> Column[In, Literal['expr']]: ...
def first_value(col: ColumnOrName[In, Out], ignoreNulls: bool | Column | None = None) -> Column[In, Literal['expr']]: ...
def last_value(col: ColumnOrName[In, Out], ignoreNulls: bool | Column | None = None) -> Column[In, Literal['expr']]: ...
def count_if(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def histogram_numeric(col: ColumnOrName[In, Out], nBins: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ntile(n: int) -> Column[In, Literal['expr']]: ...
def curdate() -> Column[In, Literal['expr']]: ...
def current_date() -> Column[In, Literal['expr']]: ...
def current_timezone() -> Column[In, Literal['expr']]: ...
def current_timestamp() -> Column[In, Literal['expr']]: ...
def now() -> Column[In, Literal['expr']]: ...
def localtimestamp() -> Column[In, Literal['expr']]: ...
def date_format(date: ColumnOrName[In, Out], format: str) -> Column[In, Literal['expr']]: ...
def year(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def quarter(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def month(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def dayofweek(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def dayofmonth(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def day(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def dayofyear(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def hour(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def minute(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def second(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def weekofyear(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def weekday(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def extract(field: ColumnOrName[In, Out], source: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def date_part(field: ColumnOrName[In, Out], source: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def datepart(field: ColumnOrName[In, Out], source: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def make_date(year: ColumnOrName[In, Out], month: ColumnOrName[In, Out], day: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def date_add(start: ColumnOrName[In, Out], days: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def dateadd(start: ColumnOrName[In, Out], days: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def date_sub(start: ColumnOrName[In, Out], days: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def datediff(end: ColumnOrName[In, Out], start: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def date_diff(end: ColumnOrName[In, Out], start: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def date_from_unix_date(days: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def add_months(start: ColumnOrName[In, Out], months: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def months_between(date1: ColumnOrName[In, Out], date2: ColumnOrName[In, Out], roundOff: bool = True) -> Column[In, Literal['expr']]: ...
def to_date(col: ColumnOrName[In, Out], format: str | None = None) -> Column[In, Literal['expr']]: ...
def unix_date(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def unix_micros(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def unix_millis(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def unix_seconds(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def to_timestamp(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def to_timestamp(col: ColumnOrName[In, Out], format: str) -> Column[In, Literal['expr']]: ...
def try_to_timestamp(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def xpath(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_boolean(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_double(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_number(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_float(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_int(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_long(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_short(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xpath_string(xml: ColumnOrName[In, Out], path: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def trunc(date: ColumnOrName[In, Out], format: str) -> Column[In, Literal['expr']]: ...
def date_trunc(format: str, timestamp: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def next_day(date: ColumnOrName[In, Out], dayOfWeek: str) -> Column[In, Literal['expr']]: ...
def last_day(date: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def from_unixtime(timestamp: ColumnOrName[In, Out], format: str = 'yyyy-MM-dd HH:mm:ss') -> Column[In, Literal['expr']]: ...
@overload
def unix_timestamp(timestamp: ColumnOrName[In, Out], format: str = ...) -> Column[In, Literal['expr']]: ...
@overload
def unix_timestamp() -> Column[In, Literal['expr']]: ...
def from_utc_timestamp(timestamp: ColumnOrName[In, Out], tz: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def to_utc_timestamp(timestamp: ColumnOrName[In, Out], tz: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def timestamp_seconds(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def timestamp_millis(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def timestamp_micros(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def window(timeColumn: ColumnOrName[In, Out], windowDuration: str, slideDuration: str | None = None, startTime: str | None = None) -> Column[In, Literal['expr']]: ...
def window_time(windowColumn: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def session_window(timeColumn: ColumnOrName[In, Out], gapDuration: Column | str) -> Column[In, Literal['expr']]: ...
def to_unix_timestamp(timestamp: ColumnOrName[In, Out], format: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def to_timestamp_ltz(timestamp: ColumnOrName[In, Out], format: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def to_timestamp_ntz(timestamp: ColumnOrName[In, Out], format: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def current_catalog() -> Column[In, Literal['expr']]: ...
def current_database() -> Column[In, Literal['expr']]: ...
def current_schema() -> Column[In, Literal['expr']]: ...
def current_user() -> Column[In, Literal['expr']]: ...
def user() -> Column[In, Literal['expr']]: ...
def crc32(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def md5(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sha1(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sha2(col: ColumnOrName[In, Out], numBits: int) -> Column[In, Literal['expr']]: ...
def hash(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def xxhash64(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def assert_true(col: ColumnOrName[In, Out], errMsg: Column | str | None = None) -> Column[In, Literal['expr']]: ...
def raise_error(errMsg: Column | str) -> Column[In, Literal['expr']]: ...
def upper(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def lower(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ascii(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def base64(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def unbase64(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ltrim(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def rtrim(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def trim(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def concat_ws(sep: str, *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def decode(col: ColumnOrName[In, Out], charset: str) -> Column[In, Literal['expr']]: ...
def encode(col: ColumnOrName[In, Out], charset: str) -> Column[In, Literal['expr']]: ...
def format_number(col: ColumnOrName[In, Out], d: int) -> Column[In, Literal['expr']]: ...
def format_string(format: str, *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def instr(str: ColumnOrName[In, Out], substr: str) -> Column[In, Literal['expr']]: ...
def overlay(src: ColumnOrName[In, Out], replace: ColumnOrName[In, Out], pos: ColumnOrName[In, Out] | int, len: ColumnOrName[In, Out] | int = -1) -> Column[In, Literal['expr']]: ...
def sentences(string: ColumnOrName[In, Out], language: ColumnOrName[In, Out] | None = None, country: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def substring(str: ColumnOrName[In, Out], pos: int, len: int) -> Column[In, Literal['expr']]: ...
def substring_index(str: ColumnOrName[In, Out], delim: str, count: int) -> Column[In, Literal['expr']]: ...
def levenshtein(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out], threshold: int | None = None) -> Column[In, Literal['expr']]: ...
def locate(substr: str, str: ColumnOrName[In, Out], pos: int = 1) -> Column[In, Literal['expr']]: ...
def lpad(col: ColumnOrName[In, Out], len: int, pad: str) -> Column[In, Literal['expr']]: ...
def rpad(col: ColumnOrName[In, Out], len: int, pad: str) -> Column[In, Literal['expr']]: ...
def repeat(col: ColumnOrName[In, Out], n: int) -> Column[In, Literal['expr']]: ...
def split(str: ColumnOrName[In, Out], pattern: str, limit: int = -1) -> Column[In, Literal['expr']]: ...
def rlike(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regexp(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regexp_like(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regexp_count(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regexp_extract(str: ColumnOrName[In, Out], pattern: str, idx: int) -> Column[In, Literal['expr']]: ...
def regexp_extract_all(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out], idx: int | Column | None = None) -> Column[In, Literal['expr']]: ...
def regexp_replace(string: ColumnOrName[In, Out], pattern: str | Column, replacement: str | Column) -> Column[In, Literal['expr']]: ...
def regexp_substr(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def regexp_instr(str: ColumnOrName[In, Out], regexp: ColumnOrName[In, Out], idx: int | Column | None = None) -> Column[In, Literal['expr']]: ...
def initcap(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def soundex(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bin(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def hex(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def unhex(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def length(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def octet_length(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bit_length(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def translate(srcCol: ColumnOrName[In, Out], matching: str, replace: str) -> Column[In, Literal['expr']]: ...
def to_binary(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def to_char(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def to_varchar(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def to_number(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def replace(src: ColumnOrName[In, Out], search: ColumnOrName[In, Out], replace: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def split_part(src: ColumnOrName[In, Out], delimiter: ColumnOrName[In, Out], partNum: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def substr(str: ColumnOrName[In, Out], pos: ColumnOrName[In, Out], len: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def parse_url(url: ColumnOrName[In, Out], partToExtract: ColumnOrName[In, Out], key: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def printf(format: ColumnOrName[In, Out], *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def url_decode(str: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def url_encode(str: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def position(substr: ColumnOrName[In, Out], str: ColumnOrName[In, Out], start: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def endswith(str: ColumnOrName[In, Out], suffix: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def startswith(str: ColumnOrName[In, Out], prefix: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def char(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def btrim(str: ColumnOrName[In, Out], trim: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def char_length(str: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def character_length(str: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def try_to_binary(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def try_to_number(col: ColumnOrName[In, Out], format: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def contains(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def elt(*inputs: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def find_in_set(str: ColumnOrName[In, Out], str_array: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def like(str: ColumnOrName[In, Out], pattern: ColumnOrName[In, Out], escapeChar: Column | None = None) -> Column[In, Literal['expr']]: ...
def ilike(str: ColumnOrName[In, Out], pattern: ColumnOrName[In, Out], escapeChar: Column | None = None) -> Column[In, Literal['expr']]: ...
def lcase(str: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def ucase(str: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def left(str: ColumnOrName[In, Out], len: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def right(str: ColumnOrName[In, Out], len: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def mask(col: ColumnOrName[In, Out], upperChar: ColumnOrName[In, Out] | None = None, lowerChar: ColumnOrName[In, Out] | None = None, digitChar: ColumnOrName[In, Out] | None = None, otherChar: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
@overload
def create_map(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def create_map(__cols: list['ColumnOrName[In, Out]_'] | tuple['ColumnOrName[In, Out]_', ...], /) -> Column[In, Literal['expr']]: ...
def map_from_arrays(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def array(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def array(__cols: list['ColumnOrName[In, Out]_'] | tuple['ColumnOrName[In, Out]_', ...], /) -> Column[In, Literal['expr']]: ...
def array_contains(col: ColumnOrName[In, Out], value: Any) -> Column[In, Literal['expr']]: ...
def arrays_overlap(a1: ColumnOrName[In, Out], a2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def slice(x: ColumnOrName[In, Out], start: ColumnOrName[In, Out] | int, length: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def array_join(col: ColumnOrName[In, Out], delimiter: str, null_replacement: str | None = None) -> Column[In, Literal['expr']]: ...
def concat(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_position(col: ColumnOrName[In, Out], value: Any) -> Column[In, Literal['expr']]: ...
def element_at(col: ColumnOrName[In, Out], extraction: Any) -> Column[In, Literal['expr']]: ...
def try_element_at(col: ColumnOrName[In, Out], extraction: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def get(col: ColumnOrName[In, Out], index: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def array_prepend(col: ColumnOrName[In, Out], value: Any) -> Column[In, Literal['expr']]: ...
def array_remove(col: ColumnOrName[In, Out], element: Any) -> Column[In, Literal['expr']]: ...
def array_distinct(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_insert(arr: ColumnOrName[In, Out], pos: ColumnOrName[In, Out] | int, value: Any) -> Column[In, Literal['expr']]: ...
def array_intersect(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_union(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_except(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_compact(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_append(col: ColumnOrName[In, Out], value: Any) -> Column[In, Literal['expr']]: ...
def explode(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def posexplode(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def inline(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def explode_outer(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def posexplode_outer(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def inline_outer(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def get_json_object(col: ColumnOrName[In, Out], path: str) -> Column[In, Literal['expr']]: ...
def json_tuple(col: ColumnOrName[In, Out], *fields: str) -> Column[In, Literal['expr']]: ...
def from_json(col: ColumnOrName[In, Out], schema: ArrayType | StructType | Column | str, options: dict[str, str] | None = None) -> Column[In, Literal['expr']]: ...
def to_json(col: ColumnOrName[In, Out], options: dict[str, str] | None = None) -> Column[In, Literal['expr']]: ...
def schema_of_json(json: ColumnOrName[In, Out], options: dict[str, str] | None = None) -> Column[In, Literal['expr']]: ...
def json_array_length(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def json_object_keys(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def schema_of_csv(csv: ColumnOrName[In, Out], options: dict[str, str] | None = None) -> Column[In, Literal['expr']]: ...
def to_csv(col: ColumnOrName[In, Out], options: dict[str, str] | None = None) -> Column[In, Literal['expr']]: ...
def size(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_min(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_max(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_size(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def cardinality(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def sort_array(col: ColumnOrName[In, Out], asc: bool = True) -> Column[In, Literal['expr']]: ...
def array_sort(col: ColumnOrName[In, Out], comparator: Callable[[Column, Column], Column] | None = None) -> Column[In, Literal['expr']]: ...
def shuffle(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def reverse(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def flatten(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def map_contains_key(col: ColumnOrName[In, Out], value: Any) -> Column[In, Literal['expr']]: ...
def map_keys(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def map_values(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def map_entries(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def map_from_entries(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def array_repeat(col: ColumnOrName[In, Out], count: ColumnOrName[In, Out] | int) -> Column[In, Literal['expr']]: ...
def arrays_zip(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def map_concat(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def map_concat(__cols: list['ColumnOrName[In, Out]_'] | tuple['ColumnOrName[In, Out]_', ...], /) -> Column[In, Literal['expr']]: ...
def sequence(start: ColumnOrName[In, Out], stop: ColumnOrName[In, Out], step: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def from_csv(col: ColumnOrName[In, Out], schema: Column | str, options: dict[str, str] | None = None) -> Column[In, Literal['expr']]: ...
@overload
def transform(col: ColumnOrName[In, Out], f: Callable[[Column], Column]) -> Column[In, Literal['expr']]: ...
@overload
def transform(col: ColumnOrName[In, Out], f: Callable[[Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def exists(col: ColumnOrName[In, Out], f: Callable[[Column], Column]) -> Column[In, Literal['expr']]: ...
def forall(col: ColumnOrName[In, Out], f: Callable[[Column], Column]) -> Column[In, Literal['expr']]: ...
@overload
def filter(col: ColumnOrName[In, Out], f: Callable[[Column], Column]) -> Column[In, Literal['expr']]: ...
@overload
def filter(col: ColumnOrName[In, Out], f: Callable[[Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def aggregate(col: ColumnOrName[In, Out], initialValue: ColumnOrName[In, Out], merge: Callable[[Column, Column], Column], finish: Callable[[Column], Column] | None = None) -> Column[In, Literal['expr']]: ...
def reduce(col: ColumnOrName[In, Out], initialValue: ColumnOrName[In, Out], merge: Callable[[Column, Column], Column], finish: Callable[[Column], Column] | None = None) -> Column[In, Literal['expr']]: ...
def zip_with(left: ColumnOrName[In, Out], right: ColumnOrName[In, Out], f: Callable[[Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def transform_keys(col: ColumnOrName[In, Out], f: Callable[[Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def transform_values(col: ColumnOrName[In, Out], f: Callable[[Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def map_filter(col: ColumnOrName[In, Out], f: Callable[[Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def map_zip_with(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out], f: Callable[[Column, Column, Column], Column]) -> Column[In, Literal['expr']]: ...
def str_to_map(text: ColumnOrName[In, Out], pairDelim: ColumnOrName[In, Out] | None = None, keyValueDelim: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def years(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def months(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def days(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def hours(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def convert_timezone(sourceTz: Column | None, targetTz: Column, sourceTs: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def make_dt_interval(days: ColumnOrName[In, Out] | None = None, hours: ColumnOrName[In, Out] | None = None, mins: ColumnOrName[In, Out] | None = None, secs: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def make_interval(years: ColumnOrName[In, Out] | None = None, months: ColumnOrName[In, Out] | None = None, weeks: ColumnOrName[In, Out] | None = None, days: ColumnOrName[In, Out] | None = None, hours: ColumnOrName[In, Out] | None = None, mins: ColumnOrName[In, Out] | None = None, secs: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def make_timestamp(years: ColumnOrName[In, Out], months: ColumnOrName[In, Out], days: ColumnOrName[In, Out], hours: ColumnOrName[In, Out], mins: ColumnOrName[In, Out], secs: ColumnOrName[In, Out], timezone: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def make_timestamp_ltz(years: ColumnOrName[In, Out], months: ColumnOrName[In, Out], days: ColumnOrName[In, Out], hours: ColumnOrName[In, Out], mins: ColumnOrName[In, Out], secs: ColumnOrName[In, Out], timezone: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def make_timestamp_ntz(years: ColumnOrName[In, Out], months: ColumnOrName[In, Out], days: ColumnOrName[In, Out], hours: ColumnOrName[In, Out], mins: ColumnOrName[In, Out], secs: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def make_ym_interval(years: ColumnOrName[In, Out] | None = None, months: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def bucket(numBuckets: Column | int, col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def call_udf(udfName: str, *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def call_function(funcName: str, *cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def unwrap_udt(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def hll_sketch_agg(col: ColumnOrName[In, Out], lgConfigK: int | Column | None = None) -> Column[In, Literal['expr']]: ...
def hll_union_agg(col: ColumnOrName[In, Out], allowDifferentLgConfigK: bool | Column | None = None) -> Column[In, Literal['expr']]: ...
def hll_sketch_estimate(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def hll_union(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out], allowDifferentLgConfigK: bool | None = None) -> Column[In, Literal['expr']]: ...
def ifnull(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def isnotnull(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def equal_null(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def nullif(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def nvl(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def nvl2(col1: ColumnOrName[In, Out], col2: ColumnOrName[In, Out], col3: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def aes_encrypt(input: ColumnOrName[In, Out], key: ColumnOrName[In, Out], mode: ColumnOrName[In, Out] | None = None, padding: ColumnOrName[In, Out] | None = None, iv: ColumnOrName[In, Out] | None = None, aad: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def aes_decrypt(input: ColumnOrName[In, Out], key: ColumnOrName[In, Out], mode: ColumnOrName[In, Out] | None = None, padding: ColumnOrName[In, Out] | None = None, aad: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def try_aes_decrypt(input: ColumnOrName[In, Out], key: ColumnOrName[In, Out], mode: ColumnOrName[In, Out] | None = None, padding: ColumnOrName[In, Out] | None = None, aad: ColumnOrName[In, Out] | None = None) -> Column[In, Literal['expr']]: ...
def sha(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def input_file_block_length() -> Column[In, Literal['expr']]: ...
def input_file_block_start() -> Column[In, Literal['expr']]: ...
def reflect(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def java_method(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def version() -> Column[In, Literal['expr']]: ...
def typeof(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def stack(*cols: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitmap_bit_position(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitmap_bucket_number(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitmap_construct_agg(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitmap_count(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
def bitmap_or_agg(col: ColumnOrName[In, Out]) -> Column[In, Literal['expr']]: ...
@overload
def udf(f: Callable[..., Any], returnType: DataTypeOrString = ..., *, useArrow: bool | None = None) -> UserDefinedFunctionLike: ...
@overload
def udf(f: DataTypeOrString | None = None, *, useArrow: bool | None = None) -> Callable[[Callable[..., Any]], 'UserDefinedFunctionLike']: ...
@overload
def udf(*, returnType: DataTypeOrString = ..., useArrow: bool | None = None) -> Callable[[Callable[..., Any]], 'UserDefinedFunctionLike']: ...
def udtf(cls: Incomplete | None = None, *, returnType: StructType | str, useArrow: bool | None = None) -> UserDefinedTableFunction | Callable[[type], 'UserDefinedTableFunction']: ...
